### ISSUE TITLE
final changes (hopefully)

### ISSUE THREAD

**Issue by rmflight** [MoseleyBioinformaticsLab/manuscript.ICIKendallTau#36]
- [x] With and without tau-max scaling in response.
- [x] Remove any MAR / MNAR acronyms.
- [x] Make all the labels for figures and tables the same, i.e. ICI-Kt, IKC, etc. I originally did long and short to make it easier to read them in the manuscript where we only have 3 comparisons *vs* the supplemental where we have way more. But I think it just adds confusion.

**Comment by hunter-moseley** [comment]
Why remove MAR and MNAR acronyms. Thought the reviewer wanted the inclusion
of this terminology.

**Comment by rmflight** [comment]
The reviewer asked us to either explain MAR / MNAR, or not use the acronyms. Given we aren't writing an imputation manuscript, I think we should go with not.
